version: "3"
services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"

  todo.api:
    image: ebahr/todo.api:latest
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: ToDo.API/Dockerfile
    depends_on:
      - sql.data